sudo: required
services:
  - docker

before_install:
  - docker build -t aheckman/react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aheckman/react_test npm test

after_success:
  - docker build -t aheckman/multi-client ./client
  - docker build -t aheckman/multi-nginx ./nginx
  - docker build -t aheckman/multi-server ./server
  - docker build -t aheckman/multi-worker ./worker
  - docker echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aheckman/multi-client
  - docker push aheckman/multi-nginx
  - docker push aheckman/multi-server
  - docker push aheckman/multi-worker




